## Basic Configuration

baseurl = "https://vlanglois.com/"
builddrafts = false
canonifyurls = false
enableEmoji = true
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"


author = "Valerie Langlois"
title = "Valerie Langlois"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Valerie Langlois"
intro = "Cognitive Psychology at CU Boulder"
description = "Post-doctoral researcher studying psycholinguistics" #<br/> \"Hello\""
authorimage = "Recent Pic of me.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "vlangloisx3"
#instagram = "<username>"
#xing = "<username>"
linkedin = "vlangloisx3"
twitter = "vlangloisx3"
#facebook = "<username>"
#google = "<username>"
#stackoverflow = "<username>"
#lastfm = "<username>"
#goodreads = "<username>"
#gitlab = "<username>"
#bitbucket = "<username>"
#fivehundredpx = "<username>"
#flickr = "<username>"
#foursquare = "<username>"
#hackernews = "<username>"
#kickstarter = "<username>"
#patreon = "<username>"
#pintrest = "<username>"
#steam = "<username>"
#reddit = "<username>"
#snapchat = "<username>"
#youtube = "<username>"
#keybase = "<username>"
#twitch = "<username>"
#soundcloud = "<username>"
#tumblr = "<username>"
#strava = "<username>"
#skype = "<username>"
#telegram = "<username>"
#whatsapp = "<username>"
email = "valeriel@live.unc.edu"

## Extras
[params.extra]
copyright = "Â© 2021. Valerie Langlois. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true

[permalinks]
post = "/:slug/"

## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "publications"
    weight = 200
    identifier = "pubs"
    url = "/pubs/"  
[[menu.main]]
    name = "resources"
    weight = 300
    identifier = "resources"
    url = "/resources/"    
[[menu.main]]
    name = "CV"
    identifier = "cv"
    weight = 400
    url = "CV-10_22_20.pdf"
